In [1]:
pip show torch

Name: torch
Version: 2.1.1
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /home/ausin/.local/lib/python3.10/site-packages
Requires: filelock, fsspec, jinja2, networkx, nvidia-cublas-cu12, nvidia-cuda-cupti-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-runtime-cu12, nvidia-cudnn-cu12, nvidia-cufft-cu12, nvidia-curand-cu12, nvidia-cusolver-cu12, nvidia-cusparse-cu12, nvidia-nccl-cu12, nvidia-nvtx-cu12, sympy, triton, typing-extensions
Required-by: 
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

vector = np.array([1, 2, 3, 4, 5])

In [3]:
vector

array([1, 2, 3, 4, 5])

In [5]:
vector.ndim

1

In [6]:
scalar = np.array(1)

In [13]:
scalar
print(scalar.ndim)

1


In [8]:
scalar = np.array([1])

In [11]:
print(scalar)
scalar.ndim

[1]


1

In [12]:
scalar
scalar

array([1])

In [14]:
scalar

array([1])

In [15]:
scalar.ndim

1

In [16]:
scalar.ndim

1